BestRestaurants/Models/BestRestaurantsContext.cs
using Microsoft.EntityFrameworkCore;

namespace BestRestaurants.Models
{
  public class BestRestaurantsContext : DbContext
  {
    public DbSet<Cuisine> Cuisines { get; set; }
    public DbSet<Restaurant> Restaurants { get; set; }
    public DbSet<Review> Reviews { get; set; }

    public BestRestaurantsContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

BestRestaurants/Models/Cuisine.cs
using System.Collections.Generic;

namespace BestRestaurants.Models
{
  public class Cuisine
  {
    public Cuisine()
    {
      this.Restaurants = new HashSet<Restaurant>();
    }

    public int CuisineId { get; set; }
    public string Type { get; set; }
    public virtual ICollection<Restaurant> Restaurants { get; set; }
  }
}

BestRestaurants/Models/Restaurant.cs
using System.Collections.Generic;

namespace BestRestaurants.Models
{
  public class Restaurant
  {
    public int RestaurantId { get; set; }
    public string Name { get; set; }
    public int MealPrice { get; set; }
    public bool Outdoor { get; set; }
    public bool Reservations { get; set; }
    public int CuisineId { get; set; }
    public virtual ICollection<Review> Reviews { get; set; }

    public virtual Cuisine Cuisine { get; set; }
  }
}

BestRestaurants/Models/Review.cs
namespace BestRestaurants.Models
{
  public class Review
  {
    public int ReviewId { get; set; }
    public string Text { get; set; }
    public int RestaurantId { get; set; }
    public virtual Restaurant Restaurant { get; set; }
  }
}

BestRestaurants/Controllers/CuisinesController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using BestRestaurants.Models;
using System.Collections.Generic;
using System.Linq;

namespace BestRestaurants.Controllers
{
  public class CuisinesController : Controller
  {
    private readonly BestRestaurantsContext _db;
    
    public CuisinesController(BestRestaurantsContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Cuisine> model = _db.Cuisines.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Cuisine cuisine)
    {
      _db.Cuisines.Add(cuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    public ActionResult Edit(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost]
    public ActionResult Edit(Cuisine cuisine)
    {
      _db.Entry(cuisine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      _db.Cuisines.Remove(thisCuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Search(int id)
    {
      List<Restaurant> model = _db.Restaurants.Where(restaurant => restaurant.CuisineId == id).ToList();
      ViewBag.Cuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(model);
    }
  }
}

BestRestaurants/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace BestRestaurants.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

BestRestaurants/Controllers/RestaurantsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using BestRestaurants.Models;
using System.Collections.Generic;
using System.Linq;

namespace BestRestaurants.Controllers
{
    public class RestaurantsController : Controller
    {
      private readonly BestRestaurantsContext _db;
      
      public RestaurantsController(BestRestaurantsContext db)
      {
        _db = db;
      }

      public ActionResult Index()
      {
        List<Restaurant> model = _db.Restaurants.Include(restaurant => restaurant.Cuisine).ToList();
        return View(model);
      }
      
      public ActionResult Create()
      {
        ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Type");
        return View();
      }
      
      [HttpPost]
      public ActionResult Create(Restaurant restaurant)
      {
        _db.Restaurants.Add(restaurant);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }

      public ActionResult Details(int id)
      {
        Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
        ViewBag.ReviewList = _db.Reviews.Where(review => review.RestaurantId == id).ToList();
        return View(thisRestaurant);
      }

      public ActionResult Edit(int id)
      {
        var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
        ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Type");
        return View(thisRestaurant);
      }
      
      [HttpPost]
      public ActionResult Edit(Restaurant restaurant)
      {
        _db.Entry(restaurant).State = EntityState.Modified;
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
      
      public ActionResult Delete(int id)
      {
        var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
        return View(thisRestaurant);
      }
      
      [HttpPost, ActionName("Delete")]
      public ActionResult DeleteConfirmed(int id)
      {
        var thisRestaurant= _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
        _db.Restaurants.Remove(thisRestaurant);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
      public ActionResult Search()
      {
        return View();
      }

      [HttpPost]
      public ActionResult Search(string name)
      {
        string searchName = name.ToLower();
        List<Restaurant> searchResults = _db.Restaurants.Where(restaurant => restaurant.Name.ToLower().Contains(searchName)).ToList();
        return View("Index", searchResults);
      }
    }
}

BestRestaurants/Controllers/ReviewsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using BestRestaurants.Models;
using System.Linq;

namespace BestRestaurants.Controllers
{
  public class ReviewsController : Controller
  {
    private readonly BestRestaurantsContext _db;

    public ReviewsController(BestRestaurantsContext db)
    {
      _db = db;
    }

    public ActionResult Create(int id)
    {
      ViewBag.Restaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      return View();
    }

    [HttpPost]
    public ActionResult Create(Review review)
    {
      _db.Reviews.Add(review);
      _db.SaveChanges();
      return RedirectToAction("Details", "Restaurants", new { id = review.RestaurantId });
    }

    public ActionResult Edit(int id)
    {
      var thisReview = _db.Reviews.FirstOrDefault(review => review.ReviewId == id);
      ViewBag.RestaurantId = new SelectList(_db.Restaurants, "RestaurantId", "Name");
      return View(thisReview);
    }

    [HttpPost]
    public ActionResult Edit(Review review)
    {
      _db.Entry(review).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", "Restaurants", new { id = review.RestaurantId });
    }

    public ActionResult Delete(int id)
    {
      var thisReview = _db.Reviews.FirstOrDefault(review => review.ReviewId == id);
      return View(thisReview);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int Id)
    {
      var thisReview = _db.Reviews.FirstOrDefault(review => review.ReviewId == Id);
      _db.Reviews.Remove(thisReview);
      _db.SaveChanges();
      return RedirectToAction("Details", "Restaurants", new { id = Id });
    }
  }
}

BestRestaurants/Views/Cuisines/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Cuisine

<div class="jumbotron">
  <h3>Add a new cuisine</h3>
</div>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Type)
  @Html.TextBoxFor(model => model.Type)
  <input type="submit" value="Add Cuisine"/>
}
<p>@Html.ActionLink("Show all cuisine options", "Index")</p>

BestRestaurants/Views/Cuisines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Cuisine

<div class="jumbotron">
  <h3>Deleting @Model.Type</h3>
</div>

<p>Are you sure?</p>

@using (Html.BeginForm())
{
  <input type="submit" value="Delete"/>
}
@Html.ActionLink("Back to Cusine List", "Index")

BestRestaurants/Views/Cuisines/Details.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Cuisine

<div class="jumbotron">
  <h3>Details</h3>
</div>
<hr/>
<h4>@Html.DisplayNameFor(model => model.Type): @Html.DisplayFor(model => model.Type)</h4>
<p>@Html.ActionLink("View Restaurants for this Cuisine", "Search", new { id = Model.CuisineId })</p>
<p>@Html.ActionLink("Edit Cuisine", "Edit", new { id = Model.CuisineId })</p>
<p>@Html.ActionLink("Delete Cuisine", "Delete", new { id = Model.CuisineId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

BestRestaurants/Views/Cuisines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Cuisine

<div class="jumbotron">
  <h3>Editing @Model.Type</h3>
</div>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.CuisineId)

  @Html.LabelFor(model => model.Type)
  @Html.EditorFor(model => model.Type)

  <input type="submit" value="Save"/>
}
<p>@Html.ActionLink("Back to list", "Index")</p>

BestRestaurants/Views/Cuisines/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models;

<div class="jumbotron">
  <h3>Cuisine Options</h3>
</div>

@if (@Model.Count == 0)
{
  <p>No cuisines have been added yet!</p>
}

<ul>
  @foreach (Cuisine cuisine in Model)
  {
    <li>@Html.ActionLink($"{cuisine.Type}", "Details", new {id = cuisine.CuisineId})</li>
  }
</ul>

<p>@Html.ActionLink("Add new cuisine", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

BestRestaurants/Views/Cuisines/Search.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models;

<div class="jumbotron">
  <h3>Restaurants for @ViewBag.Cuisine.Type</h3>
</div>

@if (Model.Count == 0)
{
  <p>No restaurants for this cuisine have been added.</p>
}

<ul>
  @foreach (Restaurant restaurant in Model)
  {
      <li>@Html.ActionLink($"{restaurant.Name}", "Details", "Restaurants", new { id = restaurant.RestaurantId })</li>
  }
</ul>

<p>@Html.ActionLink("Back to list", "Index")</p>

BestRestaurants/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<div class="jumbotron">
  <h1>The Best Restaurants in Town!</h1>
</div>

<p>@Html.ActionLink("See all cuisine options", "Index", "Cuisines")</p>
<p>@Html.ActionLink("See all restaurants", "Index", "Restaurants")</p>
<p>@Html.ActionLink("Search restaurants", "Search", "Restaurants")</p>

BestRestaurants/Views/Restaurants/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Restaurant

<div class="jumbotron">
  <h3>Add a new restaraunt</h3>
</div>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.LabelFor(model => model.MealPrice)
  @Html.TextBoxFor(model => model.MealPrice, new { @type="number", min="0", max="1000" })

  @Html.LabelFor(model => model.Cuisine)
  @Html.DropDownList("CuisineId")

  @Html.LabelFor(model => model.Outdoor)
  @Html.CheckBoxFor(model => model.Outdoor)

  @Html.LabelFor(model => model.Reservations)
  @Html.CheckBoxFor(model => model.Reservations)

  <input type="submit" value="Add new restaraunt" class="btn btn-default"/>
}
<p>@Html.ActionLink("Show all restaraunts", "Index")</p>

BestRestaurants/Views/Restaurants/Delete.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Restaurant

<div class="jumbotron">
  <h3>Deleting @Model.Name</h3>
</div>

<p>Are you sure?</p>

@using (Html.BeginForm())
{
  <input type="submit" value="Delete"/>
}
@Html.ActionLink("Back to List", "Index")

BestRestaurants/Views/Restaurants/Details.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Restaurant
@using BestRestaurants.Models

<div class="jumbotron">
  <h3>Details</h3>
</div>
<hr />
<h4>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h4>
<p>@Html.DisplayNameFor(model => model.Cuisine.Type): @Html.DisplayFor(model => model.Cuisine.Type)<br>
  Average meal price: $@Html.DisplayFor(model => model.MealPrice)</p>

@if (Model.Outdoor)
{
  <p>This restaurant has outdoor seating.</p>
}
@if (Model.Reservations)
{
  <p>This restaurant accepts reservations.</p>
}

@if (ViewBag.ReviewList.Count == 0)
{
  <p>No reviews for this restaurant have been added.</p>
}

<ul>
  @foreach (Review review in ViewBag.ReviewList)
  {
    <li>
      <p>@review.Text</p>
      <p>@Html.ActionLink("Edit Review", "Edit", "Reviews", new { id = review.ReviewId}) @Html.ActionLink("Delete Review",
      "Delete", "Reviews", new { id = review.ReviewId})</p>
    </li>

  }
</ul>

<p>@Html.ActionLink("Review this Restaurant", "Create", "Reviews", new { id = Model.RestaurantId})</p>
<p>@Html.ActionLink("Back to List", "Index")</p>
<p>@Html.ActionLink("Edit Restaurant", "Edit", new { id = Model.RestaurantId})</p>
<p>@Html.ActionLink("Delete Restaurant", "Delete", new { id = Model.RestaurantId})</p>

BestRestaurants/Views/Restaurants/Edit.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Restaurant

<div class="jumbotron">
  <h3>Editing @Model.Name</h3>
</div>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.RestaurantId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.LabelFor(model => model.MealPrice)
  @Html.EditorFor(model => model.MealPrice, new { @type="number" })

  @Html.LabelFor(model => model.Cuisine)
  @Html.DropDownList("CuisineId")

  @Html.LabelFor(model => model.Outdoor)
  @Html.CheckBoxFor(model => model.Outdoor)

  @Html.LabelFor(model => model.Reservations)
  @Html.CheckBoxFor(model => model.Reservations)

  <input type="submit" value="Save"/>
}

<p>@Html.ActionLink("Back to list", "Index")</p>

BestRestaurants/Views/Restaurants/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models;
@model List<BestRestaurants.Models.Restaurant>;

<div class="jumbotron">
  <h3>Restaurants</h3>
</div>

@if (@Model.Count == 0)
{
  <p>No restaurants have been added yet!</p>
}

<ul>
  @foreach (Restaurant restaurant in Model)
  {
    <li>@Html.ActionLink($"{restaurant.Name}", "Details", new { id = restaurant.RestaurantId }) | @restaurant.Cuisine.Type
    </li>
  }
</ul>

<p>@Html.ActionLink("Add new restaurant", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

BestRestaurants/Views/Restaurants/Search.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Restaurant

<div class="jumbotron">
  <h3>Restaurant Search</h3>
</div>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  <input type="submit" value="Search"/>
}

<p>@Html.ActionLink("See all cuisine options", "Index", "Cuisines")</p>
<p>@Html.ActionLink("See all restaurants", "Index", "Restaurants")</p>

BestRestaurants/Views/Reviews/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Review

<div class="jumbotron">
  <h3>Add a new review</h3>
</div>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Text)
  @Html.TextBoxFor(model => model.Text)

  <!-- Could not get Html Helper to work for default value -->
  <input data-val="true" data-val-required="The RestaurantId field is required." id="RestaurantId" name="RestaurantId" type="hidden" value=@ViewBag.Restaurant.RestaurantId.ToString()>

  <input type="submit" value="Add new review" class="btn btn-default"/>
}
<p>@Html.ActionLink("Show all reviews", "Index")</p>

BestRestaurants/Views/Reviews/Delete.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Review

<div class="jumbotron">
  <h3>Deleting Review</h3>
</div>

<p>Are you sure?</p>

@using (Html.BeginForm())
{
  <input type="submit" value="Delete"/>
}
@Html.ActionLink("Back to List", "Index")

BestRestaurants/Views/Reviews/Edit.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Review

<div class="jumbotron">
  <h3>Editing @Model.Text</h3>
</div>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.ReviewId)

  @Html.LabelFor(model => model.Text)
  @Html.EditorFor(model => model.Text)

  <input type="submit" value="Save"/>
}

<p>@Html.ActionLink("Back to list", "Index")</p>

BestRestaurants/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Best Restaurants</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    <div class="container">
      @RenderBody()
    </div>
  </body>
</html>